version: '3.7'

services:
  if_elements_app_prod:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: supervisord
    container_name: cf_elements_app_prod
    restart: on-failure
    environment:
      TIME_ZONE: $TIME_ZONE
      CHECK_URL_INTERVAL: $CHECK_URL_INTERVAL
      LANGUAGE_CODE: $LANGUAGE_CODE
      ALLOWED_HOSTS: $ALLOWED_HOSTS
    volumes:
      - .:/app
    ports:
      - ${DJANGO_DEV_PORT}:8000
      - ${SUPERVISOR_DEV_PROD_PORT}:9001
