version: '3.7'

services:
  if_elements_app_prod:
    image: if_elements_app_prod
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8000/api/ping/" ]
      interval: 3s
      timeout: 3s
      retries: 10
    build:
      context: .
      dockerfile: ancillaries/prod.Dockerfile
    command: supervisord
    container_name: cf_elements_app_prod
    restart: on-failure
    environment:
      TIME_ZONE: $TIME_ZONE
      CHECK_URL_INTERVAL: $CHECK_URL_INTERVAL
      LANGUAGE_CODE: $LANGUAGE_CODE
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      CSRF_TRUSTED_ORIGINS: $CSRF_TRUSTED_ORIGINS
      DOCKER_HOST_IP: $DOCKER_HOST_IP
    ports:
      - ${DJANGO_PROD_PORT}:8000
      - ${SUPERVISOR_ADMIN_PROD_PORT}:9001

  if_elements_nginx_prod:
    image: if_elements_nginx_prod
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 3s
      timeout: 3s
      retries: 10
    build:
      context: .
      dockerfile: ancillaries/prod.nginx.Dockerfile
    command: nginx
    container_name: cf_elements_nginx_prod
    restart: on-failure
    depends_on:
      - if_elements_app_prod
    ports:
      - ${NGINX_PORT}:80
