version: '3.7'


services:
  element_app_prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: supervisord
    container_name: element_app_prod_container
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - $SUPERVISOR_ADMIN_PROD_PORT:9001
    networks:
      - elements

  element_nginx_prod_service:
    image: nginx:1.21.1
    ports:
      - $DJANGO_PROD_PORT:80
    container_name: element_nginx_prod_container
    restart: on-failure
    volumes:
      - $PWD/static:/etc/static
      - $PWD/ancillaries/serveapi.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - element_app_prod_service
    networks:
      - elements

networks:
  elements:
    driver: bridge
