version: '3.7'


services:
  if_elements_app_prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: supervisord
    container_name: cf_elements_app_prod
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - ${SUPERVISOR_ADMIN_PROD_PORT}:9001

  if_elements_nginx_prod:
    image: nginx:1.21.1
    ports:
      - ${DJANGO_PROD_PORT}:80
    container_name: cf_elements_nginx_prod
    restart: on-failure
    volumes:
      - $PWD/static:/etc/static
      - $PWD/ancillaries/serveapi.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - if_elements_app_prod
